# Generated by Django 4.2 on 2023-04-30 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_link', models.CharField(default='', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('fitness', models.IntegerField()),
                ('additional_data', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
