# Generated by Django 4.2 on 2023-04-30 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_id', models.UUIDField()),
                ('square', models.IntegerField()),
                ('refuse_square', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CuttingMapInOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('map_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='CuttingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('date', models.DateField()),
                ('status_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailMapArranging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('map_id', models.UUIDField()),
                ('detail_id', models.UUIDField()),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('rotating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.UUIDField()),
                ('material_id', models.UUIDField()),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('additional_data', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('detail_id', models.UUIDField()),
                ('detail_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SheetMaterialParams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('fitness', models.IntegerField()),
                ('material_id', models.UUIDField()),
            ],
        ),
    ]
