# Generated by Django 4.2 on 2024-05-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0003_alter_cuttingmap_refuse_square_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Materials',
        ),
    ]
