version: '3'

services:
  web:
    build: ./csm-server
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - '3000:3306'
    expose:
        - '3306'
    volumes:
      - mysql-db-data:/var/lib/mysql

volumes:
      mysql-db-data:
