version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./CSM-Server
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./CSM-Server/:/usr/src/CSM-Server/
    # Открываем порт 8080 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev